name: Build

on:
  push:
    branches:
      - master

jobs: 
  publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install wheel setuptools
      - name: Build package
        run: python3 python/setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
          packages_dir: dist/